name: build

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master
  # release:
  #   types:
  #     - released

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zerocluster/node
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt update
          apt install -y git
          cd build
          npm i --ignore-scripts
          npm run build
        shell: bash
