name: build-resources

on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zerocluster/node
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          apt update
          apt install -y git
          cd build
          npm i --ignore-scripts
          npm run build
        shell: bash
